site_name: Python Crash Course, Third Edition

markdown_extensions:
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - footnotes

theme:
  name: material
  logo: images/pcc_snake_logo.png
  favicon: images/pcc_snake_favicon-48px.png
  features:
    - navigation.indexes
    - navigation.instant

  palette: 
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/toggle-switch 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode

extra_css:
  - stylesheets/extra.css

nav:
  - "Home": "index.md"
  - "What's new?": "new_in_3e.md"
  - "Setup Instructions":
    - "setup_instructions/index.md"
    - "Configuring VS Code": "setup_instructions/configuring_vs_code.md"
  - "Updates":
    - "updates/index.md"
    - "First printing": "updates/first_printing.md"
    - "Second printing": "updates/second_printing.md"
    - "Which printing do I have?": "updates/which_printing.md"
  - "Solutions":
    - "solutions/index.md"
    - "Chapter 2": "solutions/chapter_2.md"
    - "Chapter 3": "solutions/chapter_3.md"
    - "Chapter 4": "solutions/chapter_4.md"
    - "Chapter 5": "solutions/chapter_5.md"
    - "Chapter 6": "solutions/chapter_6.md"
    - "Chapter 7": "solutions/chapter_7.md"
    - "Chapter 8": "solutions/chapter_8.md"
    - "Chapter 9": "solutions/chapter_9.md"
    - "Chapter 10": "solutions/chapter_10.md"
    - "Chapter 11": "solutions/chapter_11.md"
  - "Contact": "contact.md"
  - "Newsletter": "newsletter.md"